export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'

export const SAVE_SHIPPING_ITEM = 'SAVE_SHIPPING_ITEM'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'
