export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

//get orders
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

//update payment
export const GET_PAY_REQUEST = 'GET_PAY_REQUEST'
export const GET_PAY_SUCCESS = 'GET_PAY_SUCCESS'
export const GET_PAY_FAIL = 'GET_PAY_FAIL'
export const GET_PAY_RESET = 'GET_PAY_RESET'

//profile screen -my orders
export const GET_MYORDERS_REQUEST = 'GET_MYORDERS_REQUEST'
export const GET_MYORDERS_SUCCESS = 'GET_MYORDERS_SUCCESS'
export const GET_MYORDERS_FAIL = 'GET_MYORDERS_FAIL'
export const GET_MYORDERS_RESET = 'GET_MYORDERS_RESET'
