// login logout

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
//register
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

//get logged in user
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

// update profile
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

//get admin users
export const USERSLIST_REQUEST = 'USERSLIST_REQUEST'
export const USERSLIST_SUCCESS = 'USERSLIST_SUCCESS'
export const USERSLIST_FAIL = 'USERSLIST_FAIL'
export const USERSLIST_RESET = 'USERSLIST_RESET'

export const USERSREMOVE_REQUEST = 'USERSREMOVE_REQUEST'
export const USERSREMOVE_SUCCESS = 'USERSREMOVE_SUCCESS'
export const USERSREMOVE_FAIL = 'USERSREMOVE_FAIL'
